services:
  db:
    image: postgres
    container_name: local_pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5.0-alpine3.10
    container_name: local_redis
    ports:
      - "6379:6379"
    volumes:
      - local_redisdata:/path/to/local/d–∞ta:/root/redis
    environment:
      REDIS_PASSWORD: redis

  vote:
    build: ./vote
    ports:
      - "5000:80"
    environment:
      REDIS_HOST: redis
    depends_on:
      - result

  result:
    build: ./result
    ports:
      - "4000:4000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: resultdb
    depends_on:
      - db

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

volumes:
  local_pgdata:
  local_redisdata: